### ISSUE TITLE
Server and client on same machine

### ISSUE THREAD

**Issue by navalchand** [alexandre01/UltimateLabeling#1]
Hey, How can i run the UltimateLabeling.

I have tried to install both cline and the server-side, but still unable to make it up and running. Can you please help on setup, if possible how to host both client and server-side on the same machine.

Thanks in advance

**Comment by selingok033** [comment]
@navalchand Can you achieve setup? I have tried to install both cline and server-s,de on the same machine but I haven't any idea about run them. How did your get the SSH login information (Host IP, username and password)?

Thanks for your help.

**Comment by navalchand** [comment]
Hi @selingok033, I have given a couple of tries. So we finally decided to use CVAT, we have made a few changes to add server-side inference for interpolation. Feel free to reach out to me if you need any further assistance.

**Comment by starkgate** [comment]
You can ssh into your own machine with `ssh localhost`. Make sure you have the `openssh-server` package installed.

**Comment by alemelis** [comment]
@starkgate I'm using your fork 
but when I click on `Run on frame` (either yolo or openpifpaf) I get the following error

```
$ python -m ultimatelabeling.main
Detection server started...
[2020-11-04 11:44:33,756-rk0-load_helper.py# 31] load pretrained model from res/SiamMask_VOT.pth
[2020-11-04 11:44:35,633-rk0-load_helper.py# 25] remove prefix 'module.'
[2020-11-04 11:44:35,634-rk0-load_helper.py# 18] used keys:356
Connecting to detector socket:  localhost 8786
Traceback (most recent call last):
  File "/home/alessandro/UltimateLabeling/ultimatelabeling/views/detection_manager.py", line 124, in run
    self.detector.init()
  File "/home/alessandro/UltimateLabeling/ultimatelabeling/models/detector.py", line 37, in init
    self.client_socket.connect((self.HOST, self.PORT))
ConnectionRefusedError: [Errno 111] Connection refused
Aborted (core dumped)
```

is there any additional config parameter to set?

**Comment by starkgate** [comment]
@alemelis Hi, I can see two possible causes for this:
- Either the port is already used by another app (use netstat to check)
- Or you have some kind of firewall that blocks sockets

**Comment by alemelis** [comment]
@starkgate thanks a lot for the reply

it doesn't seem to be the case; the port is not listed by `netstat` and 
```
sudo ufw allow 8786
```
yields the same error

is there any other step apart from starting the `venv` and launching the tool as
```
python -m ultimatelabeling.main
```
?

**Comment by starkgate** [comment]
There shouldn't be. Not that I remember at least. You could try using Pycharm to debug the specific line and see what is going on. I remember the error messages for sockets are pretty cryptic. Connection refused could be anything.

**Comment by nguyenminhanh301098** [comment]
Can someone give me documentation about UltimateLabeling Tool? thank you so much
